version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: taller_nodejs_db
    environment:
      MYSQL_ROOT_PASSWORD: passwordadmin
      MYSQL_DATABASE: taller_nodejs
      MYSQL_USER: rodrigo
      MYSQL_PASSWORD: lolcito123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      - nodejs-network

volumes:
  db_data:

networks:
  nodejs-network:
    driver: bridge